accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignupView.as_view(),name='signup'),
    path('',views.IndexView.as_view(),name='home'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('login/',views.LoginView.as_view(),name='login'),
    path('activate/<uidb64>/<token>/', views.ActivateAccount.as_view(), name='activate'),
    path('signup/<uuid:token>/', views.SignupView2.as_view(), name='signup2'),
    


]

api/urls.py
from django.urls import path,include
from rest_framework import routers
from . import views


router=routers.DefaultRouter()
router.register('Users',views.UserView)
router.register('Coins',views.CoinView)
router.register('Apis',views.ApiKeyView)
router.register('wallets',views.WalletView)
router.register('Registered Transactions',views.RegisteredTransactionsView)
router.register('Fund Request',views.FundRequestView)


urlpatterns = [
    path('',include(router.urls)),
    path('emailtransfer/',views.EmailTransfer.as_view(),name='email_transfer'),
]

main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cet/', include('cet.urls')),
    path('api/', include('api.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('accounts/', include('accounts.urls')),
    
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/invitation/invitation.html
{% autoescape off %}
Hey there!,  Our records show that you've received crypto from someone
To accept it you need to register and create a wallet

Here is the link to register {{ domain }}{% url 'accounts:signup2' token %}

{% endautoescape %}

templates/invitation/signup2.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Register</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="#">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">Authentication</a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">Register</a>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">

                        {% if msg %}
                        <span class="text-danger">{{ msg | safe }}</span>
                        {% else %}
                        <span>
                            Complete your credentials
                        </span>
                        {% endif %}

                    </div>
                </div>

                <form method="post" action="{% url 'accounts:signup' %}">

                    {% csrf_token %}

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-lg-4">

                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="icon-envelope"></i>
                                            </span>
                                        </div>
                                        {{email }}
                                    </div>
                                </div>
                                <span class="text-danger">{{ form.email.errors }}</span>

                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="icon-lock"></i>
                                            </span>
                                        </div>
                                        {{ form.password }}
                                        <input type="checkbox" onclick="myFunction()">Show Password
                                    </div>
                                </div>
                                <span class="text-danger">{{ form.password.errors }}</span>

                            </div>
                        </div>
                    </div>
                    <div class="card-action">
                        <button type="submit" class="btn btn-success">Submit</button>
                        &nbsp; &nbsp;
                        <span>Already have and account?</span> <a href="{% url 'accounts:login' %}">Login</a>
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script>
    function myFunction() {
        var x = document.getElementById("myInput");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }
</script>
{% endblock javascripts %}