api/urls.py
from django.urls import path,include
from rest_framework import routers
from . import views


router=routers.DefaultRouter()
router.register('Users',views.UserView)
router.register('Coins',views.CoinView)
router.register('Apis',views.ApiKeyView)
router.register('wallets',views.WalletView)
router.register('Registered Transactions',views.RegisteredTransactionsView)
router.register('Fund Request',views.FundRequestView)


urlpatterns = [
    path('',include(router.urls)),
    path('emailtransfer/',views.EmailTransfer.as_view(),name='email_transfer'),
]

cet/urls.py
from django.urls import path
from .views import WalletList,WalletCreate,WalletUpdate,WalletDelete,FundRequestView

app_name = 'cet'



urlpatterns = [
    path('manage/', WalletList.as_view(), name='manage'),
    path('create/', WalletCreate.as_view(), name='create'),
    path('update/<id>/', WalletUpdate.as_view(), name='update'),
    path('delete/<id>/', WalletDelete.as_view(), name='delete'),
    path('fundrequest/', FundRequestView.as_view(),name='fundrequest'),


]

main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cet/', include('cet.urls')),
    path('api/', include('api.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('accounts/', include('accounts.urls')),
    
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cet/models.py
from django.db import models
from cet.choices import COIN_CHOICES
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.urls import reverse
import uuid



class BaseModel(models.Model):
    created_at=models.DateTimeField(auto_now_add=True,blank=True)

    class Meta:
        abstract = True


class Coin(BaseModel):
    name=models.CharField(max_length=15,choices=COIN_CHOICES)

    def __str__(self):
        return self.name


class ApiKey(BaseModel):
    api_token=models.CharField(max_length=100)
    owner = models.ForeignKey(get_user_model(),related_name='owner_apikeys',on_delete=models.CASCADE)
    devs = models.ManyToManyField(get_user_model())
    name=models.CharField(max_length=100)
    is_verified=models.BooleanField(default=False)
    coin_type=models.ManyToManyField(Coin)
    url=models.URLField(max_length=200,blank=True,default=None)

    def __str__(self):
        return str(self.owner)

    # @receiver(post_save, sender=refrencing an admin user)
    # def create_auth_token(sender, instance=None, created=False, **kwargs):
    #     if created:
    #         Token.objects.create(user=instance)





class Wallet(BaseModel):
    name=models.CharField(max_length=200)
    owner = models.ForeignKey(get_user_model(),related_name='owner_wallet',on_delete=models.CASCADE)
    public_key=models.CharField(max_length=451)
    type= models.ForeignKey(Coin,on_delete=models.DO_NOTHING)
    auto_deposit=models.BooleanField(default=True)

    def __str__(self):
        return str(self.owner)

    




    # def type_checker(type):
    #     pass

class RegisteredTransactions(BaseModel):
    sender=models.ForeignKey(get_user_model(),on_delete=models.DO_NOTHING)
    reciever=models.EmailField()
    type=models.CharField(max_length=200)
    amount=models.DecimalField(max_digits=18,decimal_places=8)
    is_successful=models.BooleanField(default=False)

class PendingTransactions(BaseModel):
    sender=models.ForeignKey(get_user_model(),on_delete=models.DO_NOTHING)
    reciever=models.EmailField()
    type=models.CharField(max_length=200)
    amount=models.DecimalField(max_digits=18,decimal_places=8)
    is_successful=models.BooleanField(default=False)
    token=models.UUIDField(default=uuid.uuid4,editable=False)
    


class FundRequest(BaseModel):
    sender=models.EmailField(max_length=200)
    reciever=models.ForeignKey(get_user_model(),on_delete=models.DO_NOTHING)
    amount=models.DecimalField(max_digits=18,decimal_places=8)
    type=models.OneToOneField(Coin,on_delete=models.DO_NOTHING)
    security_token=models.CharField(max_length=15)
    is_successful=models.BooleanField(default=False)
    is_expired=models.BooleanField(default=False)
    expiration_date=models.DateTimeField()

cet/forms.py
from django import forms
from django.db.models import fields
from django.db.models.base import Model
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import Wallet,Coin,FundRequest
from .choices import COIN_CHOICES
User = get_user_model()



class WalletForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
            attrs={
                "placeholder" : "name",                
                "class": "form-control"
            }
        ))
    type = forms.ModelChoiceField(queryset=Coin.objects.all(),widget=forms.Select(
            attrs={               
                "class": "form-control",
                
            }
        ))
    public_key = forms.CharField(widget=forms.TextInput(
            attrs={
                "placeholder" : "Public Key",                
                "class": "form-control"
            }
        ))
    # CHOICES=[('Enable','Enable'),
    #      ('Disable','Disable')]
    # Status=forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(
    #     attrs={
           
    #          "class":"form-radio-input"
    #     }
    # ))
    
    class Meta:
        model=Wallet
        fields=('name','type','public_key','auto_deposit',)
 
class FundRequestForm(forms.ModelForm):
    
    sender = forms.EmailField(widget=forms.TextInput(
            attrs={
                "placeholder" : "sender",                
                "class": "form-control"
            }
        ))
    type = forms.ModelChoiceField(queryset=Coin.objects.all(),widget=forms.Select(
            attrs={               
                "class": "form-control",
                
            }
        ))
    amount = forms.CharField(widget=forms.TextInput(
            attrs={
                "placeholder" : "amount",                
                "class": "form-control"
            }
        ))
        
    class Meta:
        model= FundRequest
        fields=('sender',  'amount', 'type',)

cet/views.py
from django.http import request
from django.shortcuts import redirect, render
from django.views.generic import CreateView,TemplateView,FormView,ListView,DetailView,UpdateView,DeleteView
from django.views.generic.base import View
from django.contrib.auth import authenticate,login,logout,get_user_model
from .forms import WalletForm,FundRequestForm
from .models import Wallet
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.core import serializers
import requests
import json
from api import views
from django.conf import settings
from api.views import EmailTransfer
from api.views import *
from django.db.models import Q
from cet.models import PendingTransactions

User = get_user_model()


class WalletList(ListView):
    template_name="cet/manage.html"
    queryset=Wallet.objects.all()
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dataset'] =Wallet.objects.all().filter(owner=self.request.user)
        return context
    

class WalletCreate(CreateView):
    template_name="cet/create.html"
    form_class=WalletForm
    queryset=Wallet.objects.all()

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()  
        users=User.objects.values_list("email",flat=True)

        type=Wallet.objects.values_list("type",flat=True)
        print(type)

        if PendingTransactions.objects.filter(reciever__in=users).exists():
            self.SendNotification(request)
            PendingTransactions.objects.filter(reciever=self.request.user).delete()
        else:
            pass  
        return redirect("cet:manage")

    def get_queryset(self):
        return Wallet.objects.all()
    
    def SendNotification(self,request):
        url="https://webhook.servicesforfree.com/edff6a93-6031-4d30-816c-de3509b88815"
        data = serializers.serialize('json',Wallet.objects.filter(owner=self.request.user))
        requests.post(url, data=data)


class WalletUpdate(UpdateView):
    template_name="cet/update.html"
    model = Wallet
    form_class = WalletForm
    def get_object(self):
        id=self.kwargs.get("id")
        return get_object_or_404(Wallet,id=id)
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        return redirect("cet:manage")

class WalletDelete(DeleteView):
    template_name="cet/delete.html"
    model = Wallet
    context_object_name="data"

    def get_object(self):
        id=self.kwargs.get("id")
        return get_object_or_404(Wallet,id=id)

    def get_success_url(self):
        return reverse("cet:manage")

class FundRequestView(View):
    form_class = FundRequestForm
    template_name='cet/fundrequest.html'

    def get(self,request,*args,**kwargs):
        return render(request, self.template_name,{"form":self.form_class})

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            sender = form.data.get("sender")
            reciever = form.data.get("reciever")
            amount = form.data.get("amount")
            type = form.data.get("type")
            # form = request.get()

            return redirect("accounts:home")
        return render(request , self.template_name,{"form":form})


# SendNotification(self,request)

templates/cet/create.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock title %} -->

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Register</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="#">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">Authentication</a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">Register</a>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">

                        {% if msg %}
                        <span class="text-danger">{{ msg | safe }}</span>
                        {% else %}
                        <span>
                            Add Wallet
                        </span>
                        {% endif %}

                    </div>
                </div>

                <form method="post" >

                    {% csrf_token %}
                      
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-lg-4">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <div>
                                         <label>Name</label><br>
                                            {{ form.name }}
                                        </div>
                                        
                                        </div>
                                        
                                            
                                        </div>
                                        <label>Public-key</label>
                                        {{ form.public_key }}<br>
                                  
                                    
                                   <div>
                                       <label>Coin</label><br>
                                        {{form.type}} <br>
                                    </div>
                                <div>
                            </div>
                            
                        </div>
                        
                        </div>
                        <div>
                            <label>Auto Deposit</label><br />
                            <label class="form-radio-label">
                                {{form.auto_deposit}}
                        </div>
                          
                        
                    </div>
                    
                    <div class="card-action">
                        <button type="submit" class="btn btn-success">Submit</button>
                      
                        
                        
                    </div>
                    
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/cet/delete.html
{% extends "layouts/base.html" %}
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Register</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="#">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">Authentication</a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">Register</a>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">

                        {% if msg %}
                        <span class="text-danger">{{ msg | safe }}</span>
                        {% else %}
                        <span>
                            Confirm Delete
                        </span>
                        {% endif %}

                    </div>
                </div>

                <form method="post">

                    {% csrf_token %}

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-lg-4">


                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">

                                        </div>

                                    </div>

                                    <label>Are you sure you want to delete ( {{data.name}} ) wallet with public_key ({{data.public_key}})?? </label><br>
                                    



    

                        </div>

                    </div>

            </div>


            <div class="card-action">
                <button type="submit" class="btn btn-danger">Delete</button> &nbsp;&nbsp;
                <a class="btn btn-secondary" href="{% url 'cet:manage' %}">Cancel</a>
            
            </div>
            </form>

        </div>
    </div>
</div>
</div>

{% endblock content %}

templates/cet/fundrequest.html
{% extends "layouts/base.html" %}

{% block title %} UI Forms {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="pcoded-content">

    <!-- [ breadcrumb ] start -->
    <div class="page-header">

        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h5 class="m-b-10">Form Elements</h5>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="javascript:">Form Componants</a></li>
                    <li class="breadcrumb-item"><a href="javascript:">Form Elements</a></li>
                </ul>
            </div>
        </div>

    </div>
    <!-- [ breadcrumb ] end -->
    <div class="main-body">

        <!-- [ Main Content ] start -->

        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>Fund Request</h5>
                </div>
                <div class="card-body">
                    <h5>Fund Request Details</h5>
                    <hr>
                    <div class="row">
                        <div class="col-md-6">
                            <form>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Sender's Email address</label>
                                    {{form.sender}}
                                    <small id="emailHelp" class="form-text text-muted"></small>

                                </div>
                                <div class="form-group">
                                    <label for="exampleFormControlSelect1">crypto type</label>
                                    <label>Coin</label><br>
                                    {{form.type}} <br>
                                </div>
                                <div class="form-group">
                                    <label>Amount</label>
                                    {{form.amount}}
                                </div>
                                <button type="submit" class="btn btn-primary">Send Request</button>
                            </form>
                        </div>

                    </div>

                </div>
            </div>

            <!-- [ Main Content ] end -->
        </div>
    </div>

</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/cet/manage.html
{% extends "layouts/base.html" %}

{% block title %} UI Datatables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h4 class="card-title">Add Row</h4>
                <button class="btn btn-primary btn-round ml-auto" data-toggle="modal" data-target="#addRowModal">
                    <i class="fa fa-plus"></i>
                    Add Row
                </button>
            </div>
        </div>
        <div class="card-body">
            <!-- Modal -->
            <div class="modal fade" id="addRowModal" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header no-bd">
                            <h5 class="modal-title">
                                <span class="fw-mediumbold">
                                    New</span>
                                <span class="fw-light">
                                    Row
                                </span>
                            </h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p class="small">Create a new row using this form, make sure you fill them all</p>
                            <form>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group form-group-default">
                                            <label>Name</label>
                                            <input id="addName" type="text" class="form-control"
                                                placeholder="fill name">
                                        </div>
                                    </div>
                                    <div class="col-md-6 pr-0">
                                        <div class="form-group form-group-default">
                                            <label>Position</label>
                                            <input id="addPosition" type="text" class="form-control"
                                                placeholder="fill position">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group form-group-default">
                                            <label>Office</label>
                                            <input id="addOffice" type="text" class="form-control"
                                                placeholder="fill office">
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer no-bd">
                            <button type="button" id="addRowButton" class="btn btn-primary">Add</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <table id="add-row" class="display table table-striped table-hover">
                    <thead>
                        <tr><th>Wallet Namet</th>
                            <th>Public Key</th>
                            <th>Coin</th>
                            <th>Status</th>
                            <th style="width: 0%">Action</th>
                        </tr>
                    </thead>
                        {% for data in dataset %}
                   
                    <tbody>
                        <tr>
                            <td>{{data.name}}</td>
                            <td>{{data.public_key}}</td>
                            <td>{{data.type}}</td>
                            <td>{{data.auto_deposit}}</td>
                            <td>


                        
                                <div class="form-button-action">
                                    <a class="btn btn-link btn-primary btn-lg" href="{% url 'cet:update' data.id %}">Edit</a>
                                    
                                    <a class="btn btn-link btn-danger" href="{% url 'cet:delete' data.id %}" >Delete</a>
                                    
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="/static/assets/js/setting-demo2.js"></script>
<script>
    $(document).ready(function () {
        $('#basic-datatables').DataTable({
        });

        $('#multi-filter-select').DataTable({
            "pageLength": 5,
            initComplete: function () {
                this.api().columns().every(function () {
                    var column = this;
                    var select = $('<select class="form-control"><option value=""></option></select>')
                        .appendTo($(column.footer()).empty())
                        .on('change', function () {
                            var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                            );

                            column
                                .search(val ? '^' + val + '$' : '', true, false)
                                .draw();
                        });

                    column.data().unique().sort().each(function (d, j) {
                        select.append('<option value="' + d + '">' + d + '</option>')
                    });
                });
            }
        });

        // Add Row
        $('#add-row').DataTable({
            "pageLength": 5,
        });

        var action = '<td> <div class="form-button-action"> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

        $('#addRowButton').click(function () {
            $('#add-row').dataTable().fnAddData([
                $("#addName").val(),
                $("#addPosition").val(),
                $("#addOffice").val(),
                action
            ]);
            $('#addRowModal').modal('hide');

        });
    });
</script>

{% endblock javascripts %}

templates/cet/update.html
{% extends "layouts/base.html" %}
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Register</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="#">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">Authentication</a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">Register</a>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">

                        {% if msg %}
                        <span class="text-danger">{{ msg | safe }}</span>
                        {% else %}
                        <span>
                            Update Wallet
                        </span>
                        {% endif %}

                    </div>
                </div>

                <form method="post">

                    {% csrf_token %}

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-lg-4">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">

                                        <div>
                                            <label>Name</label><br>
                                            {{ form.name }}
                                        </div>
                                        
                                        </div>
                                        
                                        
                                        </div>
                                        <label>Public-key</label>
                                        {{ form.public_key }}<br>
                                        
                                        
                                <div>
                                    <label>Coin</label><br>
                                    {{form.type}} <br>
                            </div>
                    <div>
                </div>   
             </div>                         
       </div>
                            <div>
                                <label>Auto Deposit</label><br />
                                <label class="form-radio-label">
                                    {{form.auto_deposit}}
                    </div>
                                        
                                        
                </div>

            <div class="card-action">
                <button type="submit" class="btn btn-success" >Update</button> &nbsp;&nbsp;
                <a class="btn btn-secondary" href="{% url 'cet:manage' %}">Cancel</a>

            </div>
            </form>

        </div>
    </div>
</div>
</div>

{% endblock content %}